packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  return-fetch: true
  unrs-resolver: true
onlyBuiltDependencies:
  - unrs-resolver
  - prisma
  - '@prisma/engines'
  - bcrypt
  - return-fetch
patchedDependencies:
  react-native-safe-area-context@5.7.0: patches/react-native-safe-area-context@5.7.0.patch
